{
  imports = [
    ./paperlessngx.nix
    ./minecraft-server.nix
    ./arcane.nix
    ./home-assistant.nix
    ./jellyfin.nix
    ./livesync.nix
    ./opsbot.nix
    ./cluster-node.nix
    ./metasploitable.nix
    ./prometheus.nix
    ./audiobookshelf.nix
    ./immich.nix
    ./vikunja.nix
    ./netbird-server.nix
    ./stay-on.nix
    ./pihole.nix
    ./vaultwarden.nix
    ./github-runner.nix
    ./monitoring.nix
    ./stress.nix
    ./matrix-server.nix
    ./homarr.nix
    ./attic-server.nix
  ];
}
